import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { LogOut, Menu, X } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { useState } from 'react';
export const Navigation = () => {
    const { isAuthenticated, logout } = useAuth();
    const [isOpen, setIsOpen] = useState(false);
    return (_jsxs("nav", { className: "bg-gradient-to-r from-orange-600 to-orange-500 text-white py-4 px-6 shadow-lg sticky top-0 z-50", children: [_jsxs("div", { className: "max-w-7xl mx-auto flex justify-between items-center", children: [_jsx(Link, { to: "/", className: "flex items-center gap-2 hover:opacity-80 transition-opacity", children: _jsx("img", { src: "/images/logo.png", alt: "The Flex Logo", className: "h-10 w-auto" }) }), _jsxs("div", { className: "hidden md:flex items-center gap-8", children: [_jsx(Link, { to: "/", className: "hover:text-orange-100 transition-colors font-semibold", children: "Home" }), isAuthenticated && (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/dashboard", className: "hover:text-orange-100 transition-colors font-semibold", children: "Dashboard" }), _jsx(Link, { to: "/workouts", className: "hover:text-orange-100 transition-colors font-semibold", children: "Workouts" }), _jsx(Link, { to: "/profile", className: "hover:text-orange-100 transition-colors font-semibold", children: "Profile" }), _jsxs("button", { onClick: logout, className: "flex items-center gap-2 bg-white text-orange-600 hover:bg-orange-50 px-4 py-2 rounded-lg transition-colors font-semibold", children: [_jsx(LogOut, { size: 18 }), "Logout"] })] }))] }), _jsx("button", { onClick: () => setIsOpen(!isOpen), className: "md:hidden p-2 hover:bg-gray-800 rounded-lg", children: isOpen ? _jsx(X, { size: 24 }) : _jsx(Menu, { size: 24 }) })] }), isOpen && (_jsxs("div", { className: "md:hidden mt-4 pt-4 border-t border-orange-400 space-y-3", children: [_jsx(Link, { to: "/", className: "block py-2 hover:text-orange-100 transition-colors font-semibold", children: "Home" }), isAuthenticated && (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/dashboard", className: "block py-2 hover:text-orange-100 transition-colors font-semibold", children: "Dashboard" }), _jsx(Link, { to: "/workouts", className: "block py-2 hover:text-orange-100 transition-colors font-semibold", children: "Workouts" }), _jsx(Link, { to: "/profile", className: "block py-2 hover:text-orange-100 transition-colors font-semibold", children: "Profile" }), _jsxs("button", { onClick: () => {
                                    logout();
                                    setIsOpen(false);
                                }, className: "w-full flex items-center gap-2 bg-white text-orange-600 hover:bg-orange-50 px-4 py-2 rounded-lg transition-colors font-semibold", children: [_jsx(LogOut, { size: 18 }), "Logout"] })] }))] }))] }));
};
